name: your run name
project: your project name
entity: your team or user entity

# Training
device: "cuda"
wandb_log_interval: 1  # * means logging to wandb.
save_interval: 10
loss_params: {} # params configured corresponding to bc/losses.py

# Dataset
root_dir: "expert_data/dataset/conditional/benchmark_1"
nb_datapoints: -1 # * Load All availablle data
resize: [256, 256]
spline_points: 1000
shuffle: True
s: 10

# Model
bc_backbone_params: # params according to bc/models.py
  out_channels: 1

# Sweep WANDB
sweep_params:
  metric: 
    goal: minimize
    name: val/bc
  method: grid
  parameters:
    seed:
      values: [42]
    data_seed:
      values: [42, 33, 99]
    train_test_val_split: 
      values: [[0.9, 0.10]]
    lr:
      values: [0.001, 0.0005]
    bc_backbone:
      values: ["unet-skip-large", "unet-skip-medium"] # choices in bc/models.py 
    epochs: 
      values: [100]
    loss: 
      values: ["bce", "mse", "l1"] # choices in bc/losses.py
    batch_size:
      values: [32, 128]
    spline_path:
      values: [true]  
    obs: 
      values: ["full", "semi", "slim"] # choices = ("full": egm+start+target, "semi": egm+target, "slim": egm) 
  